systemctl_node:
  ros__parameters:
    services_name:
      start: "start_service"
      stop: "stop_service"
      restart: "restart_service"
      query: "query_service"
    sys_services:
    - myservice0
    - myservice1
    - myservice2
